<header class="page-hero compact"><div class="container"><div class="admin-title-row"><div><span class="section-kicker">Admin</span><h1><?= e(t('admin.mentor_requests')) ?></h1></div><div class="admin-title-actions"><a class="button button-muted" href="<?= e(query_url('/admin/mentor-requests/export.csv', ['page' => null])) ?>">↓ CSV</a><a class="button button-primary" href="/admin/mentor-requests/new">+ <?= e(t('mentor.admin_add')) ?></a></div></div><?php require BASE_PATH . '/views/admin/_menu.php'; ?></div></header>
<section class="section admin-section"><div class="container">
    <div class="admin-mini-stats"><a href="/admin/mentor-requests?status=draft"><strong><?= (int) $stats['pending_mentor_requests'] ?></strong><span><?= e(t('admin.pending_applications')) ?></span></a><a href="/admin/mentor-requests?status=published"><strong><?= (int) $stats['published_mentor_requests'] ?></strong><span><?= e(t('status.published')) ?></span></a><a href="/admin/mentor-requests"><strong><?= (int) $stats['mentor_requests'] ?></strong><span><?= e(t('common.all')) ?></span></a></div>
    <form class="admin-filter-form" action="/admin/mentor-requests" method="get">
        <label class="wide"><span><?= e(t('mentor.keyword')) ?></span><input type="search" name="q" value="<?= e($filters['q']) ?>" placeholder="<?= e(t('mentor.admin_search_placeholder')) ?>"></label>
        <label><span>Status</span><select name="status"><option value=""><?= e(t('common.all')) ?></option><option value="draft" <?= $filters['status'] === 'draft' ? 'selected' : '' ?>><?= e(t('status.pending')) ?></option><option value="published" <?= $filters['status'] === 'published' ? 'selected' : '' ?>><?= e(t('status.published')) ?></option><option value="archived" <?= $filters['status'] === 'archived' ? 'selected' : '' ?>><?= e(t('status.rejected')) ?></option></select></label>
        <label><span><?= e(t('admin.sort')) ?></span><select name="sort"><option value="newest" <?= $filters['sort'] === 'newest' ? 'selected' : '' ?>><?= e(t('admin.newest')) ?></option><option value="oldest" <?= $filters['sort'] === 'oldest' ? 'selected' : '' ?>><?= e(t('admin.oldest')) ?></option><option value="name" <?= $filters['sort'] === 'name' ? 'selected' : '' ?>><?= e(t('admin.by_name')) ?></option><option value="category" <?= $filters['sort'] === 'category' ? 'selected' : '' ?>><?= e(t('search.category')) ?></option></select></label>
        <button class="button button-primary" type="submit"><?= e(t('search.submit')) ?></button>
    </form>
    <div class="admin-panel table-wrap"><table><thead><tr><th>ID</th><th><?= e(t('mentor.contact_name')) ?></th><th><?= e(t('mentor.subject')) ?></th><th><?= e(t('search.region')) ?></th><th><?= e(t('mentor.availability')) ?></th><th>Status</th><th><?= e(t('admin.actions')) ?></th></tr></thead><tbody>
    <?php foreach ($requests as $request): ?><tr class="<?= $request['status'] === 'draft' ? 'pending-row' : '' ?>"><td><?= (int) $request['id'] ?></td><td><div class="admin-teacher"><div><strong><?= e($request['name']) ?></strong><small><?= e($request['phone']) ?></small></div></div></td><td><strong><?= e($request['subject']) ?></strong><small><?= e($request['category']) ?> · <?= e(mentor_request_budget($request)) ?></small></td><td><?= e(($request['settlement'] ?: '—') . ' / ' . ($request['region'] ?: '—')) ?></td><td><?= e($request['availability'] ?: '—') ?></td><td><span class="status status-<?= e($request['status']) ?>"><?= e(teacher_status_label((string) $request['status'])) ?></span></td><td><div class="admin-row-actions"><?php if ($request['status'] === 'published'): ?><a href="/mentor-request/<?= rawurlencode((string) $request['slug']) ?>" target="_blank"><?= e(t('mentor.view')) ?></a><?php endif; ?><a href="/admin/mentor-requests/<?= (int) $request['id'] ?>/edit"><?= e(t('admin.edit')) ?></a><?php if ($request['status'] !== 'published'): ?><form action="/admin/mentor-requests/<?= (int) $request['id'] ?>/status" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="approve"><button class="action-approve" type="submit"><?= e(t('admin.approve')) ?></button></form><?php endif; ?><?php if ($request['status'] !== 'archived'): ?><form action="/admin/mentor-requests/<?= (int) $request['id'] ?>/status" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="reject"><button class="action-reject" type="submit"><?= e(t('admin.reject')) ?></button></form><?php endif; ?></div></td></tr><?php endforeach; ?>
    <?php if (!$requests): ?><tr><td colspan="7"><div class="empty-state"><?= e(t('mentor.admin_no_results')) ?></div></td></tr><?php endif; ?>
    </tbody></table></div>
</div></section>
